### ISSUE TITLE
nice work!

### ISSUE THREAD

**Issue by aquynh** [devttys0/botox#2]
interesting tool, but your project description is now empty "No description, website, or topics provided."?

btw, Keystone is available as PyPi package, under the name "keystone-engine".

keep it up, cheers!

**Comment by devttys0** [comment]
Oh nice, that makes installation a lot easier! Thanks for the great work BTW!

**Comment by aquynh** [comment]
btw, how did you test this on Mips32? i have been trying to find a device, or Qemu image, that i can install gcc on it, but failed. any pointer?

**Comment by devttys0** [comment]
You can try one of these pre-built Qemu images: https://people.debian.org/~aurel32/qemu/mips/

**Comment by aquynh** [comment]
Yes i did, but failed: that Mips32 image limits memory to 256MB, so "apt
install gcc" complains of lacking memory.

**Comment by devttys0** [comment]
Not sure what you need gcc for? I just grabbed a binary off the Qemu image (`/bin/ls` for example), ran it through botox, copied it back to the Qemu instance and ran it there. If you need to compile your own MIPS binaries, building a cross compiler with crosstool-ng should work (https://github.com/crosstool-ng/crosstool-ng).

**Comment by aquynh** [comment]
Ok, never mind. I dont need this for botox, but for my tool that i want to
test on Mips. Thanks
